spring:
  jpa:
    database: postgresql
    database-platform: io.amtech.projectflow.app.CustomPostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

db:
  username: test
  password: test
  driverClassName: org.postgresql.Driver
  jdbcUrl: jdbc:postgresql://localhost:15432/projectflow?currentSchema=pf
  maximumPoolSize: 20
  minimumIdle: 1
  idleTimeout: 60000
