swagger:
  enabled: true
  title: "REST API Documentation"
  description: "Public API Documentation"
  version: "1.0"
  contact:
    name: "«АМ-интеллектуальные технологии»"
    url: "https://www.am-intech.ru/"
    email: "info@am-intech.ru"

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

db:
  username: test
  password: test
  driverClassName: org.postgresql.Driver
  jdbcUrl: jdbc:postgresql://localhost:15432/projectflow?currentSchema=pf
  maximumPoolSize: 20
  minimumIdle: 1
  idleTimeout: 60000